.TH blah 1
.SH OPTIONS
.TP
A
B
.\"
.\" Due to the rather silly limit of 6 args per request in some `native'
.\" *roff compilers, we have do the following to get the two-line
.\" hanging tag on one line. .PP to begin a new paragraph, then the
.\" tag, then .RS (start relative indent), the text, finally .RE
.\" (end relative indent).
.\"
.PP
A
.RS
Sentence 1

Sentence 2
.RE
.TP
A
B
