.TH A 1
.SH H
.IP Report
The report has the following format:

.B %user
.RS
.RS
Show the percentage of CPU utilization that occurred while
.RE

.B %nice
.RS
Show the percentage of CPU utilization that occurred while
.RE

.B %system
.RS
Show the percentage of CPU utilization that occurred while
.RE
.RE
