.TH EXAMPLE "1" "June 2024" "manner" "Example Man Page"

.SH NAME
example \- sample man page

.SH SYNOPSIS
.B example
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION
.\" This is a comment
.PP
Not a real command or man page!
.TP
\fB\-a\fR, \fB\-\-all\fR
a sample option
.TP
\fB\-b\fR, \fB\-\-ball\fR
another sample option
.PP

.TS
tab(@);
l l.
T{
Column 1
T}@T{
Column 2
T}
_
T{
row1
T}@T{
This is some tabular date
T}
T{
this is the second row
T}@T{
translated to an HTML <table>
T}
.TE


.SH SEE ALSO
.IP \(bu
First thing to see:
.UR https://example.com/something
Some Project
.UE .
.IP \(bu
Second thing to see.

.SH AUTHORS
This was written by
.MT author1@example.com
Author 1
.ME
and
.MT author2@example.com
Author 2
.ME .
