.TH autojump 1 "10 April 2012" "release-v22"
.SS NAME
.PP
autojump - a faster way to navigate your filesystem
.SS DESCRIPTION
.PP
autojump is a faster way to navigate your filesystem.
It works by maintaining a database of the directories you use the most
from the command line.
.PP
\f[I]Directories must be visited first before they can be jumped to.\f[]
.SS USAGE
.PP
\f[C]j\f[] is a convenience wrapper function around \f[C]autojump\f[].
Any option that can be used with \f[C]autojump\f[] can be used with
\f[C]j\f[] and vice versa.
.IP \[bu] 2
Jump To A Directory That Contains \f[C]foo\f[]:
.RS 2
.IP
.nf
\f[C]
j\ foo
\f[]
.fi
.RE
.IP \[bu] 2
Jump To A Child Directory:
.RS 2
.PP
Sometimes it\[aq]s convenient to jump to a child directory
(sub-directory of current directory) rather than typing out the full
name.
