.TH A 1
.SH H
Width of bullet: \w'\(bu'
.PP
.nr a 1n
a register is \na
.PP
.nr m \w'\(bu'
m register is \nm
.PP
.nr k \w'\(bu'+2n
k register is \nk
.PP
.nr l \w'\(bu'+2n-1
l register is \nl
.PP
.nr n \w'\(bu'+2n-1/1n
n register is \nn
.IP \(bu \nn
Choose a file name...
.IP \(bu \nn
Have A set up...
.LP
.RS
.nf
.ne 3
\f3mkdir\fP  \f2B\fP ...
.fi
.RE
.IP \(bu \nn
Have each user
