.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bzr 1 "2017\-01\-26" "2.7.0" "Bazaar"
.SH "NAME"
.SS
Checks:

  A common mistake is to forget to add a new file or directory before
  running the commit command. The \-\-strict option checks for unknown
  files and aborts the commit if any are found. More advanced pre\-commit
  checks can be implemented by defining hooks. See \\*(Aq\\*(Aqbzr help hooks\\*(Aq\\*(Aq
  for details.
