.TH ROOT 1 "Version 6" "ROOT"
.SH SYNOPSIS

.RI _\(dq_\(dq

_\(dq_\(dq

.RI A\\(dqA\\(dq

A\\(dqA\\(dq

.RI B\\\(dqB\\\(dq

B\\\(dqB\\\(dq

.RI C\\\\(dqC\\\\(dq

C\\\\(dqC\\\\(dq

.RI D\\\\\(dqD\\\\\(dq

D\\\\\(dqD\\\\\(dq

.RI E\\\\\\(dqE\\\\\\(dq

E\\\\\\(dqE\\\\\\(dq

.RI \\a

.RI \\\b

.RI \\\\c

.RI \\\\\d

