.de1 INDENT
.\" .rstReportMargin pre:
. RS \\$1
. nr rst2man-indent\\n[rst2man-indent-level] \\n[an-margin]
. nr rst2man-indent-level +1
.\" .rstReportMargin post:
..
.de UNINDENT
. RE
.\" indent \\n[an-margin]
.\" old: \\n[rst2man-indent\\n[rst2man-indent-level]]
.nr rst2man-indent-level -1
.\" new: \\n[rst2man-indent\\n[rst2man-indent-level]]
.in \\n[rst2man-indent\\n[rst2man-indent-level]]u
..
.TH A 1
.SH H
.IP "SLS File Namespace"
.sp
Note that 
.INDENT 0.0
.IP 1. 3
The ...
.IP 2. 3
.INDENT 3.0
.TP
Subdirectories can ...
.INDENT 7.0
.IP a. 3
Each sub
