.TH md 4
.SH HEADING
Some text
.TS
tab(;);
  C   -   -   -   -
  C | C | C | C | C |
| - | - | - | - | - |
| C | C | C | C | C |
| C | C | C | C | C |
| C | C | C | C | C |
| C | C | C | C | C |
| C | C | C | C | C |
| C | C | C | C | C |
| - | - | - | - | - |
  C   C   S   C   S
  C   C   S   C   S
  C   C   S   S   S
  C   C   S   S   S.
;
;Device #1;Device #2;Device #3;Device #4
0x00;0;0;1;1
0x01;2;2;3;3
\.\.\.;\.\.\.;\.\.\.;\.\.\.;\.\.\.
:;:;:;:;:
\.\.\.;\.\.\.;\.\.\.;\.\.\.;\.\.\.
0x80;254;254;255;255
;\\---------v---------/;\\---------v---------/
;RAID1;RAID1
;\\---------------------v---------------------/
;RAID0
.TE


