TH UNITS 1
.\" set handling of single quotes: 0=>straight, >0=>left and right
.nr tQ 0
.\" groff only
.if '\*(.T'utf8' .nr tQ 1
.\" non-standard devices: Windows code page 1252
.if '\*(.T'cp1252' .nr tQ 1
.if '\*(.T'ansi' .nr tQ 1
.\" Constant-width font
.de CW
.hy 0
.\" nroff can't show CW font, so enclose in single quotes
.if n \{\
.  ie \\n(.g \{\
.    \" use proper opening and closing single quotes
.    ie \\n(tQ>0 \{\
.      ie \\n(.$>2 \&\\$1\(oq\\$2\(cq\\$3
.      el \&\(oq\\$1\(cq\\$2
.    \}
.    \" ensure neutral single quotes with Tascii
.    el \{\
.      ie \\n(.$>2 \&\\$1\(aq\\$2\(aq\\$3
.      el \&\(aq\\$1\(aq\\$2
.    \}
.  \}
.  \" legacy nroff doesn't have 'aq', so use ' and hope for the best
.  el \{\
.    ie \\n(.$>2 \&\\$1'\\$2'\\$3
.    el \&'\\$1'\\$2
.  \}
.\}
.\" troff can change fonts, so no need for quotes
.if t \{\
.  ie \\n(.$>2 \&\\$1\f(CW\\$2\fR\\$3
.  el \&\f(CW\\$1\fR\\$2
.\}
.hy 14
..
.SH SYNOPSIS
.PP
.CW units
\&'bah'
